version: '3'
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    volumes:
      # persist data even if container shuts down
      - elastic01:/usr/share/elasticsearch/data

# named volumes can be managed easier using docker-compose
volumes:
  elastic01: