module.exports={
  GroupId:{ name:"GroupId", type:"int32"},
  GroupName:{name:"GroupName", type:"string"},
  Preference:{name:"Preference", type:"int32"},
  Id:{name:"Id", type:"string"},
  Product:{name:"Product", type:"string"},
  Amount:{name:"Amount", type:"int32"},
  Measure:{name:"Measure", type:"string"},
  Energie:{name:"Energie", type:"int32"},
  FatTotal:{name:"FatTotal", type:"float"},
  Protein:{name:"Protein", type:"float"},
  CarbsTotal:{name:"CarbsTotal", type:"float"},
  Sugar:{name:"Sugar", type:"float"},
  Starch:{name:"Starch", type:"float"},
  Fibre:{name:"Fibre", type:"float"},
  Water:{name:"Water", type:"float"},
  PUFA3:{name:"PUFA3", type:"float"},
  K:{name:"K", type:"float"},
  CA:{name:"CA", type:"float"},
  P:{name:"P", type:"float"},
  MG:{name:"MG", type:"float"},
  FE:{name:"FE", type:"float"},
  CU:{name:"CU", type:"float"},
  SE:{name:"SE", type:"float"},
  ZN:{name:"ZN", type:"float"},
  IOD:{name:"IOD", type:"float"},
  VITA:{name:"VITA", type:"float"},
  VITC:{name:"VITC", type:"float"},
  VITD:{name:"VITD", type:"float"},
  VITE:{name:"VITE", type:"float"},
  VITK:{name:"VITK", type:"float"},
  VITB6:{name:"VITB6", type:"float"},
  VITB12:{name:"VITB12", type:"float"}
}